set_property PACKAGE_PIN W5 [get_ports sysClock]
set_property IOSTANDARD LVCMOS33 [get_ports sysClock]
set_property PACKAGE_PIN J1 [get_ports CANSerial]
set_property IOSTANDARD LVCMOS33 [get_ports CANSerial]
set_property PACKAGE_PIN T18 [get_ports btn]
set_property IOSTANDARD LVCMOS33 [get_ports btn]
