set_property SRC_FILE_INFO {cfile:C:/Users/Eric/CodeProjects/CPE133/HRSensToCan/HRSensToCan.srcs/constrs_1/new/finalConstr.xdc rfile:../../../HRSensToCan.srcs/constrs_1/new/finalConstr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports sysClock]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports CANSerial]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports btn]
